<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.org.openygt</groupId>
        <artifactId>openygt-dms</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>dms-production</artifactId>
    <packaging>jar</packaging>
    <name>DMS Production Execution</name>

    <dependencies>
        <dependency>
            <groupId>cn.org.openygt</groupId>
            <artifactId>dms-common</artifactId>
        </dependency>
    </dependencies>
</project>
